openapi: 3.0.0
info:
  title: select-repository
  version: '1.0'
  contact:
    name: Hiroyasu Matsuhisa
    url: 'https://github.com/hmatsu47'
    email: hmatsu47@gmail.com
  license:
    name: MIT
    url: 'https://github.com/hmatsu47/select-repository-app/blob/master/LICENSE'
  description: ECRリポジトリ選択用API
servers:
  - url: 'http://localhost:3000'
paths:
  '/setting/{service_name}':
    parameters:
      - $ref: '#/components/parameters/service_name'
    post:
      summary: リリース設定の生成・更新
      operationId: postSetting
      responses:
        '200':
          $ref: '#/components/responses/settingResponse'
        default:
          $ref: '#/components/responses/errorResponse'
      description: リリース設定の生成・更新
      requestBody:
        $ref: '#/components/requestBodies/settingRequest'
      tags:
        - setting
    get:
      summary: リリース設定の取得
      operationId: getSetting
      x-internal: false
      description: リリース設定の取得
      tags:
        - setting
      responses:
        '200':
          $ref: '#/components/responses/settingResponse'
        default:
          $ref: '#/components/responses/errorResponse'
  '/repositories/{service_name}':
    parameters:
      - $ref: '#/components/parameters/service_name'
    get:
      summary: リポジトリ一覧の取得
      operationId: getRepositories
      responses:
        '200':
          $ref: '#/components/responses/repositoriesResponse'
        default:
          $ref: '#/components/responses/errorResponse'
      description: リポジトリ一覧の取得
      tags:
        - repository
  '/images/{service_name}/{repository_name}':
    get:
      summary: コンテナイメージ一覧の取得
      responses:
        '200':
          $ref: '#/components/responses/imagesResponse'
        default:
          $ref: '#/components/responses/errorResponse'
      operationId: getImages
      description: コンテナイメージ一覧の取得
      tags:
        - image
    parameters:
      - $ref: '#/components/parameters/repository_name'
      - $ref: '#/components/parameters/service_name'
  /services:
    get:
      summary: コンテナサービス一覧の取得
      tags:
        - service
      responses:
        '200':
          $ref: '#/components/responses/servicesResponse'
        default:
          $ref: '#/components/responses/errorResponse'
      operationId: getServices
      description: |
        コンテナサービス一覧の取得
components:
  schemas:
    Setting:
      title: Setting
      type: object
      description: リリース設定モデル
      x-examples: {}
      x-internal: false
      properties:
        image_uri:
          type: string
        release_at:
          type: string
          format: date-time
        is_released:
          type: boolean
      required:
        - is_released
    Repository:
      title: Repository
      x-stoplight:
        id: a5hmmb5rdowb8
      x-internal: false
      description: リポジトリモデル
      type: object
      properties:
        name:
          type: string
        uri:
          type: string
      required:
        - name
        - uri
    Image:
      title: Image
      x-stoplight:
        id: 80mchgsyg9n8w
      type: object
      x-internal: false
      description: コンテナイメージモデル
      properties:
        uri:
          type: string
        tags:
          type: array
          items:
            type: string
        size:
          type: number
        repository_name:
          type: string
        digest:
          type: string
        pushed_at:
          type: string
          format: date-time
      required:
        - uri
        - tags
        - size
        - repository_name
        - digest
        - pushed_at
    Error:
      title: Error
      x-stoplight:
        id: 9upl83w057cha
      type: object
      properties:
        message:
          type: string
      required:
        - message
      description: エラーメッセージモデル
    Service:
      title: Service
      x-stoplight:
        id: k2e3xvikf21fr
      type: object
      description: サービスモデル
      properties:
        name:
          type: string
      required:
        - name
  parameters:
    repository_name:
      name: repository_name
      in: path
      required: true
      schema:
        type: string
      description: リポジトリ名
    service_name:
      name: service_name
      in: path
      schema:
        type: string
      description: サービス名
      required: true
  requestBodies:
    settingRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Setting'
      description: リリース設定リクエストボディ
  responses:
    repositoriesResponse:
      description: リポジトリ一覧レスポンスボディ
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Repository'
    imagesResponse:
      description: コンテナイメージ一覧レスポンスボディ
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Image'
    settingResponse:
      description: リリース設定レスポンスボディ
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Setting'
    errorResponse:
      description: エラーメッセージレスポンスボディ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    servicesResponse:
      description: サービス一覧レスポンスボディ
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/Service'
  securitySchemes: {}
tags:
  - name: image
    description: コンテナイメージ
  - name: repository
    description: コンテナリポジトリ
  - name: service
    description: コンテナサービス
  - name: setting
    description: リリース設定
