openapi: 3.0.0
info:
  title: select-repository
  version: '1.0'
  contact:
    name: Hiroyasu Matsuhisa
    url: 'https://github.com/hmatsu47'
    email: hmatsu47@gmail.com
  license:
    name: MIT
    url: 'https://github.com/hmatsu47/select-repository-app/blob/master/LICENSE'
  description: ECRリポジトリ選択用API
servers:
  - url: 'http://localhost:3000'
paths:
  /setting:
    parameters: []
    post:
      summary: リリース設定の生成・更新
      operationId: postSetting
      responses:
        '200':
          $ref: '#/components/responses/settingResponse'
        default:
          $ref: '#/components/responses/errorResponse'
      description: リリース設定の生成・更新
      requestBody:
        $ref: '#/components/requestBodies/settingRequest'
      tags:
        - setting
    get:
      summary: リリース設定の取得
      operationId: getSetting
      x-internal: false
      description: リリース設定の取得
      tags:
        - setting
      responses:
        '200':
          $ref: '#/components/responses/settingResponse'
        default:
          $ref: '#/components/responses/errorResponse'
  /repositories:
    parameters: []
    get:
      summary: リポジトリ一覧の取得
      operationId: getRepositories
      responses:
        '200':
          $ref: '#/components/responses/repositoryResponse'
        default:
          $ref: '#/components/responses/errorResponse'
      description: リポジトリ一覧の取得
      tags:
        - repository
  '/images/{repository_name}':
    get:
      summary: コンテナイメージ一覧の取得
      responses:
        '200':
          $ref: '#/components/responses/imageResponse'
        default:
          $ref: '#/components/responses/errorResponse'
      operationId: getImages
      description: コンテナイメージ一覧の取得
      tags:
        - image
    parameters:
      - $ref: '#/components/parameters/repository_name'
components:
  schemas:
    Setting:
      title: Setting
      type: object
      description: リリース設定モデル
      x-examples: {}
      x-internal: false
      properties:
        image_uri:
          type: string
        release_at:
          type: string
        is_released:
          type: boolean
      required:
        - image_uri
        - release_at
        - is_released
    Repository:
      title: Repository
      x-stoplight:
        id: a5hmmb5rdowb8
      x-internal: false
      description: リポジトリモデル
      type: object
      properties:
        name:
          type: string
        uri:
          type: string
      required:
        - name
        - uri
    Image:
      title: Image
      x-stoplight:
        id: 80mchgsyg9n8w
      type: object
      x-internal: false
      description: コンテナイメージモデル
      properties:
        uri:
          type: string
        tags:
          type: array
          items:
            type: string
        size:
          type: number
        repository_name:
          type: string
        digest:
          type: string
        pushed_at:
          type: string
      required:
        - uri
        - tags
        - size
        - repository_name
        - digest
        - pushed_at
    Error:
      title: Error
      x-stoplight:
        id: 9upl83w057cha
      type: object
      properties:
        message:
          type: string
      required:
        - message
      description: エラーメッセージモデル
  parameters:
    repository_name:
      name: repository_name
      in: path
      required: true
      schema:
        type: string
      description: リポジトリ名
  requestBodies:
    settingRequest:
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Setting'
        multipart/form-data:
          schema:
            type: object
            properties: {}
      description: リリース設定リクエストボディ
  responses:
    repositoryResponse:
      description: リポジトリレスポンスボディ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Repository'
    imageResponse:
      description: コンテナイメージレスポンスボディ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Image'
    settingResponse:
      description: リリース設定レスポンスボディ
      content:
        application/xml:
          schema:
            $ref: '#/components/schemas/Setting'
    errorResponse:
      description: エラーメッセージレスポンスボディ
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  securitySchemes: {}
tags:
  - name: image
    description: コンテナイメージ
  - name: repository
    description: リポジトリ
  - name: setting
    description: リリース設定
