// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

// エラーメッセージモデル
type Error struct {
	Message string `json:"message"`
}

// コンテナイメージモデル
type Image struct {
	Digest         string   `json:"digest"`
	PushedAt       string   `json:"pushed_at"`
	RepositoryName string   `json:"repository_name"`
	Size           float32  `json:"size"`
	Tags           []string `json:"tags"`
	Uri            string   `json:"uri"`
}

// リポジトリモデル
type Repository struct {
	Name string `json:"name"`
	Uri  string `json:"uri"`
}

// リリース設定モデル
type Setting struct {
	ImageUri   string `json:"image_uri"`
	IsReleased bool   `json:"is_released"`
	ReleaseAt  string `json:"release_at"`
}

// RepositoryName defines model for repository_name.
type RepositoryName = string

// エラーメッセージモデル
type ErrorResponse = Error

// コンテナイメージモデル
type ImageResponse = Image

// リポジトリモデル
type RepositoryResponse = Repository
