// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"time"
)

// エラーメッセージモデル
type Error struct {
	Message string `json:"message"`
}

// コンテナイメージモデル
type Image struct {
	Digest         string    `json:"digest"`
	PushedAt       time.Time `json:"pushed_at"`
	RepositoryName string    `json:"repository_name"`
	Size           float32   `json:"size"`
	Tags           []string  `json:"tags"`
	Uri            string    `json:"uri"`
}

// リポジトリモデル
type Repository struct {
	Name string `json:"name"`
	Uri  string `json:"uri"`
}

// サービスモデル
type Service struct {
	Name string `json:"name"`
}

// リリース設定モデル
type Setting struct {
	ImageUri   *string    `json:"image_uri,omitempty"`
	IsReleased bool       `json:"is_released"`
	ReleaseAt  *time.Time `json:"release_at,omitempty"`
}

// RepositoryName defines model for repository_name.
type RepositoryName = string

// ServiceName defines model for service_name.
type ServiceName = string

// エラーメッセージモデル
type ErrorResponse = Error

// ImagesResponse defines model for imagesResponse.
type ImagesResponse = []Image

// RepositoriesResponse defines model for repositoriesResponse.
type RepositoriesResponse = []Repository

// ServicesResponse defines model for servicesResponse.
type ServicesResponse = []Service

// リリース設定モデル
type SettingRequest = Setting

// PostSettingJSONRequestBody defines body for PostSetting for application/json ContentType.
type PostSettingJSONRequestBody = SettingRequest
